server:
  port: 8000
spring:
  jws:
    sharedKey: 1rRa1234d567890qwertyuiopasdfghjklzxcvbnmaskdjfjasdhfjasdgf
  application:
    name: OneClickBooking
  datasource:
    url: jdbc:mysql://localhost:3306/oneclickbooking
    username: root
    password: Artem2005
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 60000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  threads:
    virtual:
      enabled: false