spring:
  jws:
    sharedKey: 1rRa1234d567890qwertyuiopasdfghjklzxcvbnmaskdjfjasdhfjasdgf
  application:
    name: OneClickBooking
  datasource:
    url: jdbc:mysql://localhost:3306/oneclickbooking
    username: ${DB_USERNAME}
    password: ${DB_USERNAME}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false